/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arvces_usbBasler_usb_basler */

#ifndef _Included_arvces_usbBasler_usb_basler
#define _Included_arvces_usbBasler_usb_basler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    InitCamera
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_arvces_usbBasler_usb_1basler_InitCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    DeInitCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_arvces_usbBasler_usb_1basler_DeInitCamera
  (JNIEnv *, jclass);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    SetExposure
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_arvces_usbBasler_usb_1basler_SetExposure
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    SetAOI
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_arvces_usbBasler_usb_1basler_SetAOI
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    SetOrientation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_arvces_usbBasler_usb_1basler_SetOrientation
  (JNIEnv *, jclass, jint);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    GetBaslerImageinArr
 * Signature: (Z)[C
 */
JNIEXPORT jcharArray JNICALL Java_arvces_usbBasler_usb_1basler_GetBaslerImageinArr
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    GetBaslerImageinArrIntArr
 * Signature: (Z)[I
 */
JNIEXPORT jintArray JNICALL Java_arvces_usbBasler_usb_1basler_GetBaslerImageinArrIntArr
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     arvces_usbBasler_usb_basler
 * Method:    SetTriggerMode
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_arvces_usbBasler_usb_1basler_SetTriggerMode
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
